-- From https://github.com/rubiin/fortune.nvim/blob/master/lua/fortune/quotes.lua

return {
  { "If you don't finish then you're just busy, not productive.", '', '- Anonymous' },
  {
    'Adapting old programs to fit new machines usually means adapting new machines to behave like old ones.',
    '',
    '- Alan Perlis',
  },
  {
    'Walking on water and developing software from a specification are easy if both are frozen.',
    '',
    '- Edward V Berard',
  },
  { 'Talk is cheap. Show me the code.', '', '- Linus Torvalds' },
  { 'In God we trust. All others must bring data.', '', '- W. Edwards Deming' },
  { "In theory, theory and practice are the same. In practice, they're not.", '', '- Yoggi Berra' },
  {
    'Programming is like sex. One mistake and you have to support it for the rest of your life.',
    '',
    '- Michael Sinz',
  },

  {
    'You can use an eraser on the drafting table or a sledgehammer on the construction site.',
    '',
    '- Frank Lloyd Wright',
  },
  {
    'System programmers are the high priests of a low cult.',
    '',
    '- Robert S. Barton',
  },
  {
    'A good programmer is someone who always looks both ways before crossing a one-way street.',
    '',
    '- Doug Linder',
  },
  {
    "I don't care if it works on your machine! We are not shipping your machine.",
    '',
    '- Vidiu Platon',
  },
  {
    'Fix the cause, not the symptom.',
    '',
    '- Steve Maguire',
  },
  {
    "It's all talk until the code runs.",
    '',
    '- Ward Cunningham',
  },
  {
    'Given enough eyeballs, all bugs are shallow.',
    '',
    '- Linus Torvalds',
  },
  {
    'A clever person solves a problem. A wise person avoids it.',
    '',
    '- Albert Einstein',
  },
  {
    'Being a good software engineer is 3% talent, 97% not being distracted by the internet.',
    '',
    '- Unknown',
  },
  {
    'Any sufficiently advanced technology is indistinguishable from magic.',
    '',
    '- Arthur C. Clarke',
  },
  {
    "A ship in port is safe, but that's not what ships are built for.",
    '',
    '- Grace Hopper',
  },
  {
    'The imposter syndrome is real. Luckily, it goes away.',
    '',
    '- Kimber Lockhart',
  },
  {
    'Know how to learn. Then, want to learn.',
    '',
    '- Katherine Johnson',
  },
  {
    "Never trust a computer you can't throw out a window.",
    '',
    '- Steve Wozniak',
  },
  {
    'When in doubt, use brute force.',
    '',
    '- Ken Thompson',
  },
  {
    'Software comes from heaven when you have good hardware.',
    '',
    '- Ken Olsen',
  },
  {
    'There is always one more bug to fix.',
    '',
    '- Ellen Ullman',
  },
  {
    'We have to stop optimizing for programmers and start optimizing for users.',
    '',
    '- Jeff Atwood',
  },
  {
    'There is a big difference between making a simple product & making a product simple.',
    '',
    '- Des Traynor',
  },
  {
    'If the code and the comments do not match, possibly both are incorrect.',
    '',
    '- Norm Schryer',
  },
  {
    'Before software can be reusable it first has to be usable.',
    '',
    '- Ralph Johnson',
  },
  {
    'If you optimize everything, you will always be unhappy.',
    '',
    '- Donald Knuth',
  },
  {
    'Testing can only prove the presence of bugs, not their absence.',
    '',
    '- Edsger W. Dijkstra',
  },
  {
    'Your most unhappy customers are your greatest source of learning.',
    '',
    '- Bill Gates',
  },
  {
    'Small minds are concerned with the extraordinary, great minds with the ordinary.',
    '',
    '- Blaise Pascal',
  },
  {
    'The most disastrous thing that you can ever learn is your first programming language.',
    '',
    '- Alan Kay',
  },
  {
    'Optimism is an occupational hazard of programming. Feedback is the treatment.',
    '',
    '- Kent Beck',
  },
  {
    "I'm not a great programmer. I'm just a good programmer with great habits.",
    '',
    '- Kent Beck',
  },
  {
    'Everyday life is like programming, I guess. If you love something, you can put beauty into it.',
    '',
    '- Donald Knuth',
  },
  { 'One of my most productive days was throwing away 1000 lines of code.', '', '- Ken Thompson' },
  {
    'Debugging becomes significantly easier if you first admit that you are the problem.',
    '',
    '- William Laeder',
  },
  { 'Computers are fast; developers keep them slow.', '', '- Peter Coffee' },
  { "Don't comment bad code - rewrite it.", '', '- Brian Kernighan' },
  { 'First, solve the problem. Then.', '', 'John Johnson' },
  { 'The computer was born to solve problems that did not exist before.', '', '- Bill Gates' },
  { 'Make it work, make it right, make it fast.', '', 'Kent Beck' },
  { 'Easy things should be easy and hard things should be possible.', '', '- Larry Wall' },
  { 'Nothing is more permanent than a temporary solution.', '', '- Fyodor Dostoevsky' },
  {
    'All programming is an exercise in caching.',
    '',
    '- Terje Mathisen',
  },
  {
    'Software is hard.',
    '',
    '- Donald Knuth',
  },
  {
    'They did not know it was impossible, so they did it!',
    '',
    '- Mark Twain',
  },
  {
    '640K ought to be enough for anybody.',
    '',
    '- Bill Gates',
  },
  {
    'To understand recursion, one must first understand recursion.',
    '',
    '- Stephen Hawking',
  },
  { 'Testing leads to failure, and failure leads to understanding.', '', '- Burt Rutan' },
  { 'The best error message is the one that never shows up.', '', '- Thomas Fuchs' },
  {
    "Don't write better error messages, write code that doesn't need them.",
    '',
    '- Jason C. McDonald',
  },
  { 'Code never lies, comments sometimes do.', '', '— Ron Jeffries' },
  { "Laziness is a programmer's main virtue.", '', '— Larry Wall' },
  { 'If, at first, you do not succeed, call it version 1.0.', '', '— Khayri R.R. Woulfe' },
  {
    'When I wrote this code, only God and I understood what I did. Now only God knows.',
    '',
    '— Martin Fowler',
  },
  {
    'What one programmer can do in one month, two programmers can do in two months.',
    '',
    '— Fred Brooks',
  },
  { 'Truth can only be found in one place: the code.', '', '- Robert C. Martin' },
  {
    'Fools ignore complexity. Pragmatists suffer it. Some can avoid it. Geniuses remove it.',
    '',
    '- Alan Perlis',
  },
  { "Code is like humor. When you have to explain it, it's bad.", '', '- Cory House' },
  {
    'The best thing about a boolean is even if you are wrong, you are only off by a bit.',
    '',
    '- Anonymous',
  },
  {
    'A LISP programmer knows the value of everything, but the cost of nothing.',
    '',
    '- Alan J. Perlis',
  },
  { 'Think twice, code once.', '', '- Anonymous' },
  { 'The sooner you start to code, the longer the program will take.', '', '- Roy Carlson' },
  {
    'No matter how far down the wrong road you have gone, turn back now.',
    '',
    '-  Turkish Proverbial Wisdom',
  },
  {
    'Why do we never have time to do it right, but always have time to do it over?',
    '',
    '- Anonymous',
  },
  { 'Weeks of programming can save you hours of planning.', '', '- Anonymous' },
  { 'To iterate is human, to recurse divine.', '', '- L. Peter Deutsch' },
  { 'Computers are useless. They can only give you answers.', '', '- Pablo Picasso' },
  { 'Almost every programming language is overrated by its practitioners.', '', '- Larry Wall' },
  { 'Fancy algorithms are slow when n is small, and n is usually small.', '', '- Rob Pike' },
  { 'Methods are just functions with a special first argument.', '', '- Andrew Gerrand' },
  {
    "If you don't make mistakes, you're not working on hard enough problems.",
    '',
    '- Frank Wilczek',
  },
  {
    "If you don't start with a spec, every piece of code you write is a patch.",
    '',
    '- Leslie Lamport',
  },
  {
    'Caches are bugs waiting to happen.',
    '',
    '- Rob Pike',
  },
  { 'All loops are infinite ones for faulty RAM modules.', '', '- Anonymous' },
  { 'All idioms must be learned. Good idioms only need to be learned once.', '', '- Alan Cooper' },
  {
    "If you don't fail at least 90% of the time, you're not aiming high enough.",
    '',
    '- Alan Kay',
  },
}
